# http://wiki.ros.org/base_local_planner#Parameters
TrajectoryPlannerROS:

  # Robot configuration
  acc_lim_x: 1.0
  acc_lim_theta: 2.0
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.4
  escape_vel: -0.1
  holonomic_robot: false

  # Goal tolerance
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  # Forward simulation
  sim_time: 3.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20

  # Trajectory scoring
  meter_scoring: true
  path_distance_bias: 0.5
  goal_distance_bias: 0.3
  occdist_scale: 0.005
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true
  publish_cost_grid_pc: false
  global_frame_id: odom

  # Oscillation
  oscillation_reset_dist: 0.05

  # Global plan
  prune_plan: true
