# http://wiki.ros.org/gmapping#Parameters

# ROS wrapper parameters
throttle_scans: 1
base_frame: base_footprint
odom_frame: odom
map_frame: map
map_update_interval: 5.0
transform_publish_period: 0.05

# Laser parameters
maxUrange: 4.0
maxRange: 5.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 0.0
occ_thresh: 0.25

# Motion model parameters
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2

# Likelihood parameters
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005

# Other parameters
linearUpdate: 0.1
angularUpdate: 0.1
temporalUpdate: -1.0
resampleThreshold: 0.5
particles: 10

# Initial map dimensions and resolution
xmin: -10.0
xmax: 10.0
ymin: -10.0
ymax: 10.0
delta: 0.02